// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8Ckt78ruJMY3VjCHm0i0-Qb7ElAiqS4',
    appId: '1:729200849890:web:2679f326802cfe5be87fbb',
    messagingSenderId: '729200849890',
    projectId: 'quizzly-firebase-ai-app',
    authDomain: 'quizzly-firebase-ai-app.firebaseapp.com',
    storageBucket: 'quizzly-firebase-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhA5DOmerqA6bwd1AMFj0F82BbyMl7VRQ',
    appId: '1:729200849890:android:37f7ea6ffbb30c1fe87fbb',
    messagingSenderId: '729200849890',
    projectId: 'quizzly-firebase-ai-app',
    storageBucket: 'quizzly-firebase-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMrFoOaT5rIUakO5PlDrhAe6lTGTgXCFU',
    appId: '1:729200849890:ios:3421006f24c789dee87fbb',
    messagingSenderId: '729200849890',
    projectId: 'quizzly-firebase-ai-app',
    storageBucket: 'quizzly-firebase-ai-app.firebasestorage.app',
    iosClientId: '729200849890-6tgbfele7qntfqkio0euaedekside76d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMrFoOaT5rIUakO5PlDrhAe6lTGTgXCFU',
    appId: '1:729200849890:ios:3421006f24c789dee87fbb',
    messagingSenderId: '729200849890',
    projectId: 'quizzly-firebase-ai-app',
    storageBucket: 'quizzly-firebase-ai-app.firebasestorage.app',
    iosClientId: '729200849890-6tgbfele7qntfqkio0euaedekside76d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB8Ckt78ruJMY3VjCHm0i0-Qb7ElAiqS4',
    appId: '1:729200849890:web:6f3b8b6459cca9c1e87fbb',
    messagingSenderId: '729200849890',
    projectId: 'quizzly-firebase-ai-app',
    authDomain: 'quizzly-firebase-ai-app.firebaseapp.com',
    storageBucket: 'quizzly-firebase-ai-app.firebasestorage.app',
  );
}
